# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import mango_mock_pb2 as mango__mock__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mango_mock_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ApprovalServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateClaim = channel.unary_unary(
                '/mango.mock.v1.ApprovalService/CreateClaim',
                request_serializer=mango__mock__pb2.CreateClaimRequest.SerializeToString,
                response_deserializer=mango__mock__pb2.ClaimReply.FromString,
                _registered_method=True)
        self.ActClaim = channel.unary_unary(
                '/mango.mock.v1.ApprovalService/ActClaim',
                request_serializer=mango__mock__pb2.ActClaimRequest.SerializeToString,
                response_deserializer=mango__mock__pb2.ClaimReply.FromString,
                _registered_method=True)
        self.GetClaim = channel.unary_unary(
                '/mango.mock.v1.ApprovalService/GetClaim',
                request_serializer=mango__mock__pb2.GetClaimRequest.SerializeToString,
                response_deserializer=mango__mock__pb2.ClaimReply.FromString,
                _registered_method=True)


class ApprovalServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateClaim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActClaim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClaim(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApprovalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateClaim': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateClaim,
                    request_deserializer=mango__mock__pb2.CreateClaimRequest.FromString,
                    response_serializer=mango__mock__pb2.ClaimReply.SerializeToString,
            ),
            'ActClaim': grpc.unary_unary_rpc_method_handler(
                    servicer.ActClaim,
                    request_deserializer=mango__mock__pb2.ActClaimRequest.FromString,
                    response_serializer=mango__mock__pb2.ClaimReply.SerializeToString,
            ),
            'GetClaim': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClaim,
                    request_deserializer=mango__mock__pb2.GetClaimRequest.FromString,
                    response_serializer=mango__mock__pb2.ClaimReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mango.mock.v1.ApprovalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mango.mock.v1.ApprovalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApprovalService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateClaim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mango.mock.v1.ApprovalService/CreateClaim',
            mango__mock__pb2.CreateClaimRequest.SerializeToString,
            mango__mock__pb2.ClaimReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActClaim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mango.mock.v1.ApprovalService/ActClaim',
            mango__mock__pb2.ActClaimRequest.SerializeToString,
            mango__mock__pb2.ClaimReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClaim(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mango.mock.v1.ApprovalService/GetClaim',
            mango__mock__pb2.GetClaimRequest.SerializeToString,
            mango__mock__pb2.ClaimReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReviewServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartReview = channel.unary_unary(
                '/mango.mock.v1.ReviewService/StartReview',
                request_serializer=mango__mock__pb2.StartReviewRequest.SerializeToString,
                response_deserializer=mango__mock__pb2.ReviewReply.FromString,
                _registered_method=True)
        self.GetReview = channel.unary_unary(
                '/mango.mock.v1.ReviewService/GetReview',
                request_serializer=mango__mock__pb2.GetReviewRequest.SerializeToString,
                response_deserializer=mango__mock__pb2.ReviewReply.FromString,
                _registered_method=True)
        self.WatchReview = channel.unary_stream(
                '/mango.mock.v1.ReviewService/WatchReview',
                request_serializer=mango__mock__pb2.GetReviewRequest.SerializeToString,
                response_deserializer=mango__mock__pb2.ReviewReply.FromString,
                _registered_method=True)


class ReviewServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchReview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReviewServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartReview': grpc.unary_unary_rpc_method_handler(
                    servicer.StartReview,
                    request_deserializer=mango__mock__pb2.StartReviewRequest.FromString,
                    response_serializer=mango__mock__pb2.ReviewReply.SerializeToString,
            ),
            'GetReview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReview,
                    request_deserializer=mango__mock__pb2.GetReviewRequest.FromString,
                    response_serializer=mango__mock__pb2.ReviewReply.SerializeToString,
            ),
            'WatchReview': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchReview,
                    request_deserializer=mango__mock__pb2.GetReviewRequest.FromString,
                    response_serializer=mango__mock__pb2.ReviewReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mango.mock.v1.ReviewService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mango.mock.v1.ReviewService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReviewService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mango.mock.v1.ReviewService/StartReview',
            mango__mock__pb2.StartReviewRequest.SerializeToString,
            mango__mock__pb2.ReviewReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mango.mock.v1.ReviewService/GetReview',
            mango__mock__pb2.GetReviewRequest.SerializeToString,
            mango__mock__pb2.ReviewReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mango.mock.v1.ReviewService/WatchReview',
            mango__mock__pb2.GetReviewRequest.SerializeToString,
            mango__mock__pb2.ReviewReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TestLabServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UnaryEcho = channel.unary_unary(
                '/mango.mock.v1.TestLabService/UnaryEcho',
                request_serializer=mango__mock__pb2.EchoRequest.SerializeToString,
                response_deserializer=mango__mock__pb2.EchoReply.FromString,
                _registered_method=True)
        self.ServerStream = channel.unary_stream(
                '/mango.mock.v1.TestLabService/ServerStream',
                request_serializer=mango__mock__pb2.StreamRequest.SerializeToString,
                response_deserializer=mango__mock__pb2.StreamItem.FromString,
                _registered_method=True)
        self.ClientStream = channel.stream_unary(
                '/mango.mock.v1.TestLabService/ClientStream',
                request_serializer=mango__mock__pb2.StreamItem.SerializeToString,
                response_deserializer=mango__mock__pb2.StreamSummary.FromString,
                _registered_method=True)
        self.BidirectionalChat = channel.stream_stream(
                '/mango.mock.v1.TestLabService/BidirectionalChat',
                request_serializer=mango__mock__pb2.ChatMessage.SerializeToString,
                response_deserializer=mango__mock__pb2.ChatMessage.FromString,
                _registered_method=True)
        self.Fail = channel.unary_unary(
                '/mango.mock.v1.TestLabService/Fail',
                request_serializer=mango__mock__pb2.FailRequest.SerializeToString,
                response_deserializer=mango__mock__pb2.EchoReply.FromString,
                _registered_method=True)
        self.Delay = channel.unary_unary(
                '/mango.mock.v1.TestLabService/Delay',
                request_serializer=mango__mock__pb2.DelayRequest.SerializeToString,
                response_deserializer=mango__mock__pb2.EchoReply.FromString,
                _registered_method=True)
        self.VersionedContract = channel.unary_unary(
                '/mango.mock.v1.TestLabService/VersionedContract',
                request_serializer=mango__mock__pb2.ContractVersionRequest.SerializeToString,
                response_deserializer=mango__mock__pb2.ContractVersionReply.FromString,
                _registered_method=True)


class TestLabServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UnaryEcho(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BidirectionalChat(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VersionedContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestLabServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UnaryEcho': grpc.unary_unary_rpc_method_handler(
                    servicer.UnaryEcho,
                    request_deserializer=mango__mock__pb2.EchoRequest.FromString,
                    response_serializer=mango__mock__pb2.EchoReply.SerializeToString,
            ),
            'ServerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerStream,
                    request_deserializer=mango__mock__pb2.StreamRequest.FromString,
                    response_serializer=mango__mock__pb2.StreamItem.SerializeToString,
            ),
            'ClientStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientStream,
                    request_deserializer=mango__mock__pb2.StreamItem.FromString,
                    response_serializer=mango__mock__pb2.StreamSummary.SerializeToString,
            ),
            'BidirectionalChat': grpc.stream_stream_rpc_method_handler(
                    servicer.BidirectionalChat,
                    request_deserializer=mango__mock__pb2.ChatMessage.FromString,
                    response_serializer=mango__mock__pb2.ChatMessage.SerializeToString,
            ),
            'Fail': grpc.unary_unary_rpc_method_handler(
                    servicer.Fail,
                    request_deserializer=mango__mock__pb2.FailRequest.FromString,
                    response_serializer=mango__mock__pb2.EchoReply.SerializeToString,
            ),
            'Delay': grpc.unary_unary_rpc_method_handler(
                    servicer.Delay,
                    request_deserializer=mango__mock__pb2.DelayRequest.FromString,
                    response_serializer=mango__mock__pb2.EchoReply.SerializeToString,
            ),
            'VersionedContract': grpc.unary_unary_rpc_method_handler(
                    servicer.VersionedContract,
                    request_deserializer=mango__mock__pb2.ContractVersionRequest.FromString,
                    response_serializer=mango__mock__pb2.ContractVersionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mango.mock.v1.TestLabService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mango.mock.v1.TestLabService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TestLabService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UnaryEcho(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mango.mock.v1.TestLabService/UnaryEcho',
            mango__mock__pb2.EchoRequest.SerializeToString,
            mango__mock__pb2.EchoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mango.mock.v1.TestLabService/ServerStream',
            mango__mock__pb2.StreamRequest.SerializeToString,
            mango__mock__pb2.StreamItem.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/mango.mock.v1.TestLabService/ClientStream',
            mango__mock__pb2.StreamItem.SerializeToString,
            mango__mock__pb2.StreamSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BidirectionalChat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/mango.mock.v1.TestLabService/BidirectionalChat',
            mango__mock__pb2.ChatMessage.SerializeToString,
            mango__mock__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Fail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mango.mock.v1.TestLabService/Fail',
            mango__mock__pb2.FailRequest.SerializeToString,
            mango__mock__pb2.EchoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mango.mock.v1.TestLabService/Delay',
            mango__mock__pb2.DelayRequest.SerializeToString,
            mango__mock__pb2.EchoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VersionedContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mango.mock.v1.TestLabService/VersionedContract',
            mango__mock__pb2.ContractVersionRequest.SerializeToString,
            mango__mock__pb2.ContractVersionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
