# 项目名称
project_name: 'GrowKnows'
# 测试人员名称
tester_name: '毛鹏'

# 测试环境
test:
  # 域名
  host: 'https://cdxptest.zalldata.cn/'
  # 默认请求头
  header: { }
  notification_type: 0
  # 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
  excel_report: False
  mysql_db:
    host: '123456'
    port: 3306
    user: 'root'
    password: '123456'

# 预发环境
pre:
  host: 'https://cdxppre.zalldata.cn/'
  header: { }
  # 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
  # 支持同时发送多个通知，如多个，则用逗号分割， 如 1, 2
  notification_type: 0
  # 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
  excel_report: False
  mysql_db:
    host: '123456'
    port: 3306
    user: 'root'
    password: '123456'

#线上环境
pro:
  host: 'https://cdxp.growknows.cn/'
  header: { }
  # 报告通知类型：0: 不发送通知 1：钉钉 2：企业微信通知 3、邮箱通知 4、飞书通知
  # 支持同时发送多个通知，如多个，则用逗号分割， 如 1, 2
  notification_type: 0
  # 收集失败的用例开关，整理成excel报告的形式，自动发送，目前只支持返送企业微信通知
  excel_report: False
  mysql_db:
    host: '123456'
    port: 3306
    user: 'root'
    password: '123456'


# 企业通知的相关配置
wechat:
  webhook: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=22748687-fa3b-4e48-a5d7-0502cef422b4'

# 邮箱
email:
  send_user: 'haha'
  email_host: 'smtp.qq.com'
  # 自己到QQ邮箱中配置stamp_key
  stamp_key: 'haha'
  # 收件人改成自己的邮箱
  send_list: [ haha,haha ]