import re

from playwright.sync_api import Page, expect


def test_example(page: Page) -> None:
    page.get_by_role("button", name="登 录").click()
    page.locator("li").filter(has_text="策略").locator("svg").click()
    page.get_by_text("用户", exact=True).click()
    with page.expect_popup() as page1_info:
        page.get_by_text("0-0cf2153f-86d6-4b37-a600-").nth(1).click()
    page1 = page1_info.value
    page1.get_by_text("行为动作").click()
    page1.get_by_role("menuitem", name="用户").locator("svg").click()
    page1.get_by_role("menuitem", name="微智助手").locator("span").click()
    page1.locator("div:nth-child(4) > div > div:nth-child(2) > .item-title > .title > .icon-down").click()
    page1.get_by_text("朋友圈群发").first.click()
    page1.get_by_text("客户群发").first.click()
    page1.get_by_role("cell", name="客户群发-016").locator("span").click()
    page1.locator(".mask").click()
    page1.get_by_role("menuitem", name="分析").locator("svg").click()
    page1.get_by_text("事件分析").click()
    page1.get_by_text("事件", exact=True).first.click()
    page1.get_by_label("事件指标").locator("#optionScroll0").get_by_text("order").click()
    page1.get_by_text("用户数").click()
    page1.get_by_text("事件", exact=True).first.click()
    page1.get_by_role("tabpanel").locator("#optionScroll0").get_by_text("order").click()
    page1.locator("#dropdown-menu-8464").get_by_text("用户数").click()
    page1.get_by_text("开始分析计算").click()
    page1.get_by_text("维度", exact=True).click()
    page1.get_by_role("button", name="请选择属性").click()
    page1.locator("#optionScroll_event_1").get_by_text("t_sdk_version").click()
    page1.get_by_role("button", name="t_sdk_version").click()
    page1.get_by_role("textbox", name="输入关键字搜索").click()
    page1.get_by_role("textbox", name="输入关键字搜索").fill("")
    page1.locator("#optionScroll_event_1").get_by_text("t_email").click()
    page.get_by_placeholder("用户名").click()
    page.get_by_placeholder("用户名").fill("zesk_system")
    page.get_by_role("button", name="登 录").click()
    page.frame_locator("iframe").get_by_text("发起流程").click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"Start_Process_Page_0\"]").locator(".awsui-public-box-title > .awsui-iconfont").first.click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"e8311951-fe18-488d-aa58-d82ff26411f9\"]").get_by_text("客户政策变更单", exact=True).click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_placeholder("选择前请先保存数据，以便带出商机销售政策和独立报价业务数据").click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_label("商机名称").get_by_text("").click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_placeholder("模糊检索:商机编号,商机名称,客户名称").click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_placeholder("模糊检索:商机编号,商机名称,客户名称").fill("顶顶顶")
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_placeholder("模糊检索:商机编号,商机名称,客户名称").click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_placeholder("模糊检索:商机编号,商机名称,客户名称").fill("测试12")
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_label("立项变更单选择商机").get_by_text("").click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_role("row", name="ZESK20240109-SJ00067 测试12").locator("span").nth(1).click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_role("button", name="确定").click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").locator("div").filter(has_text=re.compile(r"^1\.000$")).nth(1).click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_role("row", name="巨量引擎-AD 信息流 竞价一类 客户自运营 竞价充值业务 返货 0 0").get_by_role("textbox").dblclick()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_role("row", name="巨量引擎-AD 信息流 竞价一类 客户自运营 竞价充值业务 返货 0 0").get_by_role("textbox").click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_role("row", name="巨量引擎-AD 信息流 竞价一类 客户自运营 竞价充值业务 返货 0 0").get_by_role("textbox").fill("121.000")
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").locator("label").filter(has_text="作废").locator("span").nth(1).click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_placeholder("请选择").click()
    page.frame_locator("iframe").frame_locator("iframe[name=\"dataFrame\"]").frame_locator("iframe[name=\"formFrame\"]").get_by_text("A+").click()
